name: Lean 4 Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Update dependencies
        run: |
          lake update  # mathlibの依存関係を解決
          lake exe cache get  # ビルド済みのmathlibを取得（時間を短縮）

      - name: Build project
        run: |
          lake build
